In [14]:
import numpy as np
import sys
sys.path.append('..')
from common.layers import MatMul
from common.util import preprocess

c = np.array([[1, 0, 0, 0, 0, 0, 0]])
W = np.random.randn(7, 3)
layer = MatMul(W)
h = layer.forward(c)
print(h)


[[ 0.74919594 -1.32901017  1.26600499]]


In [15]:
c0 = np.array([[1, 0, 0, 0, 0, 0, 0]])
c1 = np.array([[0, 0, 1, 0, 0, 0, 0]])

W_in = np.random.randn(7, 3)
W_out = np.random.randn(3, 7)

in_layer0 = MatMul(W_in)
in_layer1 = MatMul(W_in)
out_layer0 = MatMul(W_out)

h0 = in_layer0.forward(c0)
h1 = in_layer1.forward(c1)
h = 0.5 * (h0 + h1)
s = out_layer0.forward(h)

print(h0, h1)
print(s)

[[ 0.20748633 -1.43701692  0.56498248]] [[-0.51987715 -0.35436433 -1.45515668]]
[[-0.35318113  1.80493485 -1.28608174  2.0015822  -0.46613322  1.93264658
  -1.94458755]]


In [16]:
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)
print(corpus)

[0 1 2 3 4 1 5 6]


In [17]:
def create_contexts_target(corpus, window_size=1):
  target = corpus[window_size: -window_size]
  contexts = []
  
  for idx in range(-window_size, len(corpus) -window_size):
    cs = []
    for t in range(-window_size, window_size + 1):
      if t == 0:
        continue
      cs.append(corpus[idx + t])
    contexts.append(cs)
  return np.array(contexts), np.array(target)

contexts, target = create_contexts_target(corpus, window_size=1)
print(contexts)
print(target)

[[5 0]
 [6 1]
 [0 2]
 [1 3]
 [2 4]
 [3 1]
 [4 5]
 [1 6]]
[1 2 3 4 1 5]
